{% set name = "warp-lang" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/warp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7273f4bd22a3571c357540fb0ad7dc8b9ac2578cdb1a06e0cbd0ff8907d1e064
  patches:
    - 01-find_g++_env.patch
    - 02-add_macro_def_build.patch
    - 03-install_deps_llvm_conda.patch
    - 04-find_nvcc_env.patch

build:
  string: cpu{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  script:
    - set CUTLASS_PATH=%cd%  # [win and cuda_compiler_version != "None"
    - export CUTLASS_PATH=$(pwd)  # [unix and cuda_compiler_version != "None"]
    - export CUDA_INSTALL_PATH=$(which nvcc | awk -F'/bin/nvcc' '{print $1}')  # [unix]
    - {{ PYTHON }} build_lib.py
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --no-cache-dir
  number: 2
  skip: true  # [osx or cuda_compiler_version == "11.2"]
  skip: true  # [win and cuda_compiler_version != "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cmake
    - ninja
  host:
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - python
    - pip
    - gitpython
    - numpy
  run:
    - __cuda   # [cuda_compiler_version != "None"]
    - python
    - numpy
    - jax  # [not win]
    - scipy
    - treelib
    - typeguard

test:
  imports:
    - warp
  commands:
    - pip check
    # Testing main functionalities to avoid OOM errors
    - python -m warp.tests -s autodetect -p 'test_c*.py' -p 'test_m*.py' -p 'test_s*.py'
  requires:
    - python
    - pip
    - pytest

about:
  home: https://github.com/NVIDIA/warp
  summary: 'A Python framework for high-performance simulation and graphics programming.'
  license: LicenseRef-NvidiaProprietary
  license_file:
    - copyright.py
    - LICENSE.md
    - warp/native/cutlass/LICENSE.txt
    - licenses/llvm-LICENSE.txt

extra:
  recipe-maintainers:
    - flferretti
    - traversaro
