{% set name = "warp-lang" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/warp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dc12968214b675105625b248ea750e3db9601afe129da04559260e5359ed18a0
  patches:
    - 01-find_g++_env.patch
    - 02-add_macro_def_build.patch
    - 03-install_deps_llvm_conda.patch

build:
  script:
    - {{ PYTHON }} build_lib.py
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --no-cache-dir
  number: 1
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - gitpython
    - numpy
  run:
    - python

test:
  imports:
    - warp
  commands:
    - pip check
    # Python tests require CUDA 11.5
    # - {{ PYTHON }} -m warp.test 
  requires:
    - pip
    - pytest

about:
  home: https://github.com/NVIDIA/warp
  summary: 'A Python framework for high-performance simulation and graphics programming.'
  license: LicenseRef-NVIDIA-warp
  license_file:
    - copyright.py
    - LICENSE.md
    - warp/native/cutlass/LICENSE.txt
    - licenses/llvm-LICENSE.txt

extra:
  recipe-maintainers:
    - flferretti
    - traversaro
