{% set name = "warp-lang" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/warp/archive/refs/tags/v{{ version }}.zip
  sha256: 97a8140a8bc81ea583525eef6d74efc5ca60e9d6e1d5eca092b4f648c73c8179
  patches:
    - 01-find_g++_env.patch
    - 02-add_macro_def_build.patch
    - 03-install_deps_llvm_conda.patch
    - 04-find_nvcc_env.patch

build:
  string: cpu{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  number: 1
  skip: true  # [cuda_compiler_version == "11.2" or (cuda_compiler_version != "None" and win)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - {{ stdlib("c") }}
    - cmake
    - cuda-nvrtc-dev             # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvrtc-static          # [(cuda_compiler_version or "").startswith("12")]
    - libnvjitlink-dev           # [(cuda_compiler_version or "").startswith("12")]
    - libnvjitlink-static        # [(cuda_compiler_version or "").startswith("12")]
    - libmathdx-dev ==0.1.2      # [(cuda_compiler_version or "").startswith("12") and linux]
    - libmathdx-static ==0.1.2   # [(cuda_compiler_version or "").startswith("12") and linux]
    - ninja
  host:
    - cuda-cudart-dev    # [(cuda_compiler_version or "").startswith("12") and win]
    - cuda-nvcc          # [(cuda_compiler_version or "").startswith("12") and win]
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - python
    - pip
    - setuptools
    - gitpython
    - numpy
  run:
    - __cuda   # [cuda_compiler_version != "None"]
    - jax      # [not win]
    - python
    - scipy
    - treelib
    - typeguard

test:
  imports:
    - warp
  commands:
    - pip check
    # Testing main functionalities to avoid OOM errors
    - python -m warp.tests -s autodetect -p 'test_c*.py' -p 'test_m*.py' -p 'test_s*.py'
    - python -c "import warp; warp.init(); exit(not warp.context.runtime.core.is_mathdx_enabled())"  # [(cuda_compiler_version or "").startswith("12") and linux]
  requires:
    - python
    - pip
    - pytest

about:
  home: https://github.com/NVIDIA/warp
  summary: 'A Python framework for high-performance simulation and graphics programming.'
  license: Apache-2.0 AND MIT AND CC0-1.0 AND LicenseRef-NvidiaProprietary
  license_file:
    - LICENSE.md
    - licenses/appdirs-LICENSE.txt
    - licenses/fp16-LICENSE.txt
    - licenses/Gaia-LICENSE.txt
    - licenses/llvm-LICENSE.txt
    - licenses/moller-LICENSE.txt
    - licenses/nanovdb-LICENSE.txt
    - licenses/svd-LICENSE.txt
    - licenses/unittest_parallel-LICENSE.txt
    - licenses/usd-LICENSE.txt

extra:
  recipe-maintainers:
    - shi-eric
    - flferretti
    - traversaro
