# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: "1.10.1"

package:
  name: "warp-lang"
  version: ${{ version }}

source:
  url: https://github.com/NVIDIA/warp/archive/refs/tags/v${{ version }}.zip
  sha256: 2d05ae04fb6559dc54a07c5e193031f18f3542aacd2feba9b4325ef1b8b1e516
  patches:
    - 01-avoid_static_cuda_libs.patch

build:
  number: 0
  string: ${{ "cpu" if cuda_compiler_version == "None" else "cuda" + (cuda_compiler_version | replace('.', '')) }}_h${{ hash }}_${{ build }}
  skip: (osx and x86_64)

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: cuda_compiler_version != "None"
      then:
        - ${{ compiler('cuda') }}
        - cuda-cudart-dev
        - cuda-nvrtc-dev
        - cuda-nvrtc-static
        - libnvjitlink-dev
        - libnvjitlink-static
        - libnvptxcompiler-dev
        - libmathdx-dev
        - libmathdx-static
        - if: win
          then: cuda-cudart-static
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
        - numpy
    - cmake
    - llvmdev
    - ninja
  host:
    - if: cuda_compiler_version != "None"
      then:
        - cuda-version ${{ cuda_compiler_version }}.*
    - python
    - pip
    - setuptools
    - gitpython
    - numpy
  run:
    - if: cuda_compiler_version != "None"
      then:
        - __cuda
        - cuda-cudart
        - cuda-nvrtc
        - libnvjitlink
        - libmathdx
    - if: unix
      then: jax
    - python

tests:
  - python:
      imports:
        - warp
  - script:
      - pip check
    # Testing main functionalities to avoid OOM errors
      - python -m warp.tests -s autodetect -p "test_c*.py" -p "test_m*.py" -p "test_s*.py"
      - if: cuda_compiler_version != "None" and linux
        then: python -c "import warp; warp.init(); exit(not warp.context.runtime.core.wp_is_mathdx_enabled())"
    requirements:
      run:
        - pip
        - pytest
        - python

about:
  homepage: https://github.com/NVIDIA/warp
  summary: 'A Python framework for high-performance simulation and graphics programming.'
  license: Apache-2.0 AND MIT AND CC0-1.0 AND LicenseRef-NvidiaProprietary
  license_file:
    - LICENSE.md
    - licenses/appdirs-LICENSE.txt
    - licenses/fp16-LICENSE.txt
    - licenses/Gaia-LICENSE.txt
    - licenses/moller-LICENSE.txt
    - licenses/nanovdb-LICENSE.txt
    - licenses/svd-LICENSE.txt
    - licenses/unittest_parallel-LICENSE.txt
    - licenses/usd-LICENSE.txt

extra:
  recipe-maintainers:
    - flferretti
    - traversaro
    - shi-eric
