# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: "1.9.1"

package:
  name: "warp-lang"
  version: ${{ version }}

source:
  url: https://github.com/NVIDIA/warp/archive/refs/tags/v${{ version }}.zip
  sha256: d7f2e867ec25ec4eb91e2ee66a62da2c63845986315e9ad03f2fe7a3638544d9
  patches:
    - 01-find_g++_env.patch
    - 02-disable_vsvars64.patch
    - 03-install_deps_llvm_conda.patch
    - 04-find_nvcc_env.patch
    - 05-python_3.14.patch

build:
  number: 1
  string: ${{ "cpu" if cuda_compiler_version == "None" else "cuda" + (cuda_compiler_version | replace('.', '')) }}_h${{ hash }}_${{ build }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: cuda_compiler_version != "None"
      then: ${{ compiler('cuda') }}
    - ${{ stdlib("c") }}
    - cmake
    - if: cuda_compiler_version != "None"
      then:
        - cuda-cudart-dev
        - cuda-nvrtc-dev
        - cuda-nvrtc-static
        - libnvjitlink-dev
        - libnvjitlink-static
        - libnvptxcompiler-dev
        - libmathdx-dev
        - libmathdx-static
        - if: win
          then: cuda-cudart-static
    - ninja
  host:
    - if: cuda_compiler_version != "None"
      then: cuda-version ${{ cuda_compiler_version }}.*
    - python
    - pip
    - setuptools
    - gitpython
    - numpy
  run:
    - if: cuda_compiler_version != "None"
      then: __cuda
    - if: unix
      then: jax
    - python

tests:
  - python:
      imports:
        - warp
  - script:
      - pip check
    # Testing main functionalities to avoid OOM errors
      - python -m warp.tests -s autodetect -p "test_c*.py" -p "test_m*.py" -p "test_s*.py"
      - if: cuda_compiler_version != "None" and linux
        then: python -c "import warp; warp.init(); exit(not warp.context.runtime.core.wp_is_mathdx_enabled())"
    requirements:
      run:
        - pip
        - pytest
        - python

about:
  homepage: https://github.com/NVIDIA/warp
  summary: 'A Python framework for high-performance simulation and graphics programming.'
  license: Apache-2.0 AND MIT AND CC0-1.0 AND LicenseRef-NvidiaProprietary
  license_file:
    - LICENSE.md
    - licenses/appdirs-LICENSE.txt
    - licenses/fp16-LICENSE.txt
    - licenses/Gaia-LICENSE.txt
    - licenses/llvm-LICENSE.txt
    - licenses/moller-LICENSE.txt
    - licenses/nanovdb-LICENSE.txt
    - licenses/svd-LICENSE.txt
    - licenses/unittest_parallel-LICENSE.txt
    - licenses/usd-LICENSE.txt

extra:
  recipe-maintainers:
    - flferretti
    - traversaro
    - shi-eric
